import { WhiteboardDrill } from './whiteboardDrillData';

export const TEAM_CIRCUIT_DRILLS: WhiteboardDrill[] = [
  {
    id: 'team-drill-1',
    category: 'TEAM',
    categoryLabel: 'Team Defense & Tackling Circuits',
    title: '4-CORNER PURSUIT & SWARM',
    subtitle: '11 Hats to the Ball & Pursuit Angles',
    objective: 'Every single defender takes a correct pursuit angle to the ballcarrier without following the runner. Teach running through the whistle and swarming as a unit.',
    setup: 'Set 4 cones at the four corners of a 30x40 yard field section. Full starting 11 lines up in base defensive alignment. Coach stands at QB position with football on a stick. Ballcarrier lines up 5 yards behind coach.',
    instructions: [
      'Defense gets set in base front on coach’s cadence.',
      'On ball movement, coach tosses football to the ballcarrier who sprints toward one of the 4 corner cones.',
      'Cornerback attacks downhill to set the hard edge and force the runner inside.',
      'Defensive Line and Linebackers take unique inside-out pursuit angles—never running behind a teammate.',
      'Free Safety caps the play from the top, sealing the cutback and boundary.',
      'All 11 players sprint at top speed until the coach blows the whistle, converging within 2 yards of the runner and touching up with active feet.',
    ],
    equipment: '4 cones at field corners, football on a stick, whistle.',
    diagramKeys: [
      { text: 'Never follow a teammate: take a unique angle', isHighlight: false },
      { text: 'Sprint full speed until the whistle blows', isHighlight: false },
      { text: 'Inside-out pursuit path protects cutback', isHighlight: false },
      { text: '11 guys on the tackle every play', isHighlight: true },
    ],
    cues: [
      '"Inside-out angle!"',
      '"Do NOT follow your teammate!"',
      '"Sprint through the whistle!"',
      '"ALL 11 HATS ON THE BALL!"',
    ],
    faults: [
      'Loafing or watching when play goes to the opposite sideline.',
      'Taking a flat angle and getting beaten around the perimeter.',
      'Slowing down before the coach blows the whistle.',
    ],
    phases: [
      {
        name: 'PHASE 1: SNAP & FLOW RECOGNITION',
        description: 'Offense shows toss sweep right. Front lines up pursuit angles, boundary players check cutback/bootleg.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 350, y: 195, color: '#1e293b', isSquare: true },
          { id: 'o-rb', type: 'O', label: 'RB', x: 440, y: 150, color: '#b91c1c' },
          { id: 'cone-1', type: 'cone', label: 'CONE R', x: 630, y: 140, color: '#ea580c' },
          { id: 'd-de-strong', type: 'X', label: 'DE', x: 480, y: 270, color: '#0052cc' },
          { id: 'd-dt', type: 'X', label: 'DT', x: 390, y: 270, color: '#0052cc' },
          { id: 'd-mlb', type: 'letter', label: 'M', x: 350, y: 340, color: '#0f172a' },
          { id: 'd-wlb', type: 'letter', label: 'W', x: 260, y: 340, color: '#0f172a' },
          { id: 'd-fs', type: 'letter', label: 'FS', x: 350, y: 440, color: '#0f172a' },
          { id: 'd-cb', type: 'letter', label: 'C', x: 570, y: 320, color: '#0f172a' },
        ],
        arrows: [
          { id: 'a-rb-sweep', type: 'straight', startX: 440, startY: 150, endX: 630, endY: 140, color: '#b91c1c', label: 'Toss Sweep' },
          { id: 'a-cb-force', type: 'straight', startX: 570, startY: 320, endX: 590, endY: 170, color: '#2563eb', label: 'Force Angle' },
          { id: 'a-mlb-angle', type: 'blitz', startX: 350, startY: 340, endX: 530, endY: 180, color: '#058538', label: 'Inside-Out Angle' },
          { id: 'a-fs-top', type: 'blitz', startX: 350, startY: 440, endX: 570, endY: 220, color: '#7c3aed', label: 'Over The Top' },
        ],
        zones: [],
      },
      {
        name: 'PHASE 2: THE 11-MAN SWARM',
        description: 'Ballcarrier is contained at the sideline. All 11 defenders collapse with active feet and celebrate the stop.',
        tokens: [
          { id: 'o-rb', type: 'O', label: 'RB', x: 540, y: 175, color: '#b91c1c' },
          { id: 'd-cb', type: 'letter', label: 'C', x: 615, y: 155, color: '#0f172a', subLabel: 'Corner Force' },
          { id: 'd-mlb', type: 'letter', label: 'M', x: 480, y: 235, color: '#058538', subLabel: 'Inside Fill' },
          { id: 'd-fs', type: 'letter', label: 'FS', x: 565, y: 260, color: '#7c3aed', subLabel: 'Top Cap' },
          { id: 'd-de', type: 'letter', label: 'DE', x: 450, y: 165, color: '#0052cc', subLabel: 'Contain' },
        ],
        arrows: [
          { id: 'a-swarm-cb', type: 'straight', startX: 615, startY: 155, endX: 575, endY: 170, color: '#0f172a' },
          { id: 'a-swarm-mlb', type: 'straight', startX: 480, startY: 235, endX: 520, endY: 195, color: '#058538' },
          { id: 'a-swarm-fs', type: 'straight', startX: 565, startY: 260, endX: 545, endY: 205, color: '#7c3aed' },
          { id: 'a-swarm-de', type: 'straight', startX: 450, startY: 165, endX: 505, endY: 170, color: '#0052cc' },
        ],
        zones: [
          { id: 'z-swarm', name: '11 TO THE BALL', cx: 535, cy: 195, rx: 90, ry: 55, color: '#058538', opacity: 0.25 },
        ],
      },
    ],
  },
  {
    id: 'team-drill-2',
    category: 'TEAM',
    categoryLabel: 'Team Defense & Tackling Circuits',
    title: 'HAWK PROFILE TACKLE',
    subtitle: 'Near Shoulder, Eyes to Thighs, Wrap & Squeeze',
    objective: 'Safest youth tackling technique: Remove the head from contact completely. Track the near hip, drive the near shoulder into the strike zone, wrap the thighs and roll/squeeze.',
    setup: 'Set 2 cones 5 yards apart forming a tackling chute. Tackler starts at one end in breakdown stance; partner rolls tackling donut ring or carries soft hand shield toward opposite end.',
    instructions: [
      'Tackler assumes good athletic posture with flat back, eyes forward, weight on balls of feet.',
      'As target enters the chute, tackler buzzes feet and tracks the target’s near hip.',
      'Head is kept behind the body: "Eyes to the thighs—head across is BANNED."',
      'Drive the near shoulder into the center of the thigh zone with explosive hip lift.',
      'Shoot both arms around the back of the thighs, lock hands together, squeeze tightly, and roll with momentum onto your side/back.',
    ],
    equipment: 'Tackling ring / donut bag or soft agility shield.',
    diagramKeys: [
      { text: 'Eyes to the thighs: head across is BANNED', isHighlight: false },
      { text: 'Near foot, near shoulder contact', isHighlight: false },
      { text: 'Violent double-arm wrap & squeeze', isHighlight: false },
      { text: 'Roll onto your back to finish safely', isHighlight: true },
    ],
    cues: [
      '"Track the near hip!"',
      '"Eyes to thighs!"',
      '"Near shoulder strike!"',
      '"Wrap and squeeze the knees!"',
    ],
    faults: [
      'Dropping the crown of the helmet (Safety penalty & injury risk).',
      'Diving with arms instead of driving with the hips and feet.',
      'Failing to clamp and wrap arms through contact.',
    ],
    phases: [
      {
        name: 'PHASE 1: TRACK & SINK HIPS',
        description: 'Defender buzzes feet in athletic breakdown, tracking the ballcarrier’s near hip angle.',
        tokens: [
          { id: 'bag-tackle', type: 'bag', label: 'RING BAG', x: 350, y: 160, color: '#ef4444' },
          { id: 'd-tackler', type: 'X', label: 'TACKLER', x: 350, y: 340, color: '#058538', subLabel: 'Track Near Hip' },
          { id: 'cone-l', type: 'cone', label: 'CORRIDOR', x: 240, y: 250, color: '#ea580c' },
          { id: 'cone-r', type: 'cone', label: 'CORRIDOR', x: 460, y: 250, color: '#ea580c' },
        ],
        arrows: [
          { id: 'a-buzz', type: 'straight', startX: 350, startY: 320, endX: 350, endY: 220, color: '#058538', label: 'Shimmy & Match' },
        ],
        zones: [
          { id: 'z-strike', name: 'THIGH STRIKE ZONE', cx: 350, cy: 175, rx: 65, ry: 28, color: '#058538', opacity: 0.2 },
        ],
      },
      {
        name: 'PHASE 2: NEAR SHOULDER & WRAP',
        description: 'Drive near shoulder into the sweet spot, lock arms around the legs, squeeze and roll to the ground.',
        tokens: [
          { id: 'bag-tackle', type: 'bag', label: 'RING BAG', x: 290, y: 220, color: '#ef4444' },
          { id: 'd-tackler', type: 'X', label: 'TACKLER', x: 410, y: 220, color: '#058538', subLabel: 'Clamp & Roll' },
        ],
        arrows: [
          { id: 'a-wrap', type: 'straight', startX: 410, startY: 220, endX: 330, endY: 220, color: '#058538', label: 'Wrap & Roll' },
        ],
        zones: [],
      },
    ],
  },
  {
    id: 'team-drill-3',
    category: 'TEAM',
    categoryLabel: 'Team Defense & Tackling Circuits',
    title: '3-MAN TURNOVER CIRCUIT',
    subtitle: 'Tackle, Punch, Scoop & Score Relay',
    objective: 'Teach youth defenders that the first man secures the tackle while the second man attacks the football with a tomahawk chop or punch, and the third scoops and scores.',
    setup: 'Set 1 running back carrying a football with both arms high and tight. Station 3 defenders staggered 5, 8, and 12 yards away in pursuit lines.',
    instructions: [
      'Defender 1 initiates contact and clamps around the runner’s waist/legs ("FIRST MAN WRAP").',
      'Defender 2 flies in, ignores the body, and violently punches or rakes the football downward with a tomahawk chop ("SECOND MAN STRIP").',
      'Once the football hits the turf, Defender 3 scoops the ball cleanly with two hands without falling down ("THIRD MAN SCOOP").',
      'Defender 3 secures the ball high and tight and sprints 15 yards into the end zone, while Defenders 1 & 2 peel out to form lead blocks.',
    ],
    equipment: 'Footballs, blocking pads, whistle.',
    diagramKeys: [
      { text: 'Man 1: Secure the tackle with both arms', isHighlight: false },
      { text: 'Man 2: Violent punch / tomahawk rake', isHighlight: false },
      { text: 'Man 3: Scoop and run to the end zone', isHighlight: true },
    ],
    cues: ['"First man WRAP!"', '"Second man STRIP!"', '"Third man SCOOP AND SCORE!"'],
    faults: ['First tackler trying to strip instead of securing the runner first.'],
    phases: [
      {
        name: 'PHASE 1: SECURE & STRIP',
        description: 'Tackler 1 locks up runner. Tackler 2 rakes ball downward. Third defender scoops the loose ball.',
        tokens: [
          { id: 'o-rb', type: 'O', label: 'RB', x: 350, y: 160, color: '#b91c1c' },
          { id: 'd-1', type: 'X', label: 'TACKLE 1', x: 260, y: 220, color: '#2563eb', subLabel: 'Wrap Body' },
          { id: 'd-2', type: 'X', label: 'STRIP 2', x: 440, y: 180, color: '#ea580c', subLabel: 'Tomahawk Punch' },
          { id: 'd-3', type: 'X', label: 'TRAIL 3', x: 350, y: 330, color: '#058538', subLabel: 'Scoop Relay' },
        ],
        arrows: [
          { id: 'a-strip', type: 'blitz', startX: 440, startY: 180, endX: 385, endY: 165, color: '#ea580c', label: 'Tomahawk Punch' },
          { id: 'a-scoop', type: 'blitz', startX: 350, startY: 330, endX: 350, endY: 240, color: '#058538', label: 'Scoop & Score' },
        ],
        zones: [],
      },
    ],
  },
  {
    id: 'team-drill-4',
    category: 'TEAM',
    categoryLabel: 'Team Defense & Tackling Circuits',
    title: 'GOAL LINE STAND (4TH & INCHES)',
    subtitle: 'Low-Pad Leverage & Sub-Level Push',
    objective: 'Prevent the QB sneak and fullback dive on 4th & inches. Defense wins with pad level below the offensive knee level.',
    setup: 'Offense lines up with Center and 2 Guards inside the 1-yard line. Defensive Nose Tackle and Defensive Tackle line up in 4-point stances in A-gaps. Middle Linebacker aligns 2 yards back.',
    instructions: [
      'NT and DT get into 4-point stances with eyes on the football.',
      'On snap: fire hips forward and low, targeting the center and guard’s ankles and knees ("sub-level spike").',
      'Create a human roadblock directly on the line of scrimmage, denying any forward surge.',
      'Middle Linebacker reads the QB sneak or fullback dive over the top, stepping downhill to meet the airborne runner chest-to-chest and knock them backwards.',
    ],
    equipment: 'Goal line cones, football.',
    cues: ['"Pads lower than theirs!"', '"Fire forward on movement!"', '"Build a brick wall!"'],
    faults: ['Rising up and letting the center surge forward.'],
    phases: [
      {
        name: 'PHASE 1: 4-POINT GOAL LINE SURGE',
        description: 'Nose tackle and linebackers fire under the center and guards to create a pileup at the goal line.',
        tokens: [
          { id: 'o-lg', type: 'O', label: 'LG', x: 270, y: 170, color: '#1e293b' },
          { id: 'o-c', type: 'square', label: 'C', x: 350, y: 170, color: '#1e293b', isSquare: true },
          { id: 'o-rg', type: 'O', label: 'RG', x: 430, y: 170, color: '#1e293b' },
          { id: 'o-qb', type: 'O', label: 'QB', x: 350, y: 110, color: '#b91c1c' },
          { id: 'd-nt', type: 'letter', label: 'NT', subLabel: 'A-Gap Spike', x: 310, y: 250, color: '#0052cc' },
          { id: 'd-dt', type: 'letter', label: 'DT', subLabel: 'A-Gap Spike', x: 390, y: 250, color: '#0052cc' },
          { id: 'd-mlb', type: 'letter', label: 'M', subLabel: 'Top Wedge Fill', x: 350, y: 340, color: '#b91c1c' },
        ],
        arrows: [
          { id: 'a-nt-surge', type: 'blitz', startX: 310, startY: 250, endX: 330, endY: 195, color: '#0052cc', label: 'Sub-Level Spike' },
          { id: 'a-dt-surge', type: 'blitz', startX: 390, startY: 250, endX: 370, endY: 195, color: '#0052cc', label: 'Sub-Level Spike' },
          { id: 'a-mlb-over', type: 'blitz', startX: 350, startY: 340, endX: 350, endY: 275, color: '#b91c1c', label: 'Top Wedge Fill' },
        ],
        zones: [],
      },
    ],
  },
];
