import { WhiteboardDrill } from './whiteboardDrillData';

export const EXTRA_YOUTH_DRILLS: WhiteboardDrill[] = [
  {
    id: 'dl-drill-extra-1',
    category: 'DL',
    categoryLabel: 'Defensive Tackles (DL)',
    title: 'NT 2-GAP BULLET & SPILL',
    subtitle: 'Nose Tackle Center Dominance & A-Gap Control',
    objective: 'Nose tackle strikes center on the snap, peeks into backfield flow, locks out the block, and sheds into the ballcarrier’s running lane.',
    setup: 'Set 2 orange cones 3 yards apart simulating A-gap boundaries. Center lines up with football. Running back aligns 4 yards deep in backfield. Nose Tackle coils in 3-point stance head-up on Center (0-Tech).',
    instructions: [
      'Nose Tackle coils in low 3-point stance with weight 60/40 forward on down hand.',
      'On ball movement, fire a 6-inch power step and punch both hands violently into the center’s breastplate (thumbs up, elbows tight).',
      'Lock out arms instantly to prevent the center from reaching the chest.',
      'Read the running back’s initial step: if flow goes right, shed the center into the right A-gap; if flow goes left, rip into the left A-gap.',
      'Wrap both arms around the ballcarrier’s thighs and drive cleats through the tackle.',
    ],
    equipment: 'Cones, blocking sled or heavy hand shield, football on stick.',
    cues: ['"Nose on numbers!"', '"Strike the chest plate!"', '"Shed to the football!"'],
    faults: ['Catching the block with chest instead of hands.', 'Losing sight of the running back.'],
    phases: [
      {
        name: 'PHASE 1: STRIKE & LOCKOUT',
        description: 'Snap of ball: NT explodes out of 3-point stance with thumbs up into center breastplate.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 350, y: 200, color: '#1e293b', isSquare: true },
          { id: 'd-nt', type: 'X', label: 'NT', x: 350, y: 275, color: '#2563eb', subLabel: '0-Tech' },
          { id: 'o-rb', type: 'O', label: 'RB', x: 290, y: 135, color: '#b91c1c' },
        ],
        arrows: [
          { id: 'a-punch', type: 'straight', startX: 350, startY: 260, endX: 350, endY: 220, color: '#2563eb', label: 'Double Punch' },
          { id: 'a-shed', type: 'blitz', startX: 350, startY: 220, endX: 305, endY: 155, color: '#058538', label: 'Rip & Tackle' },
        ],
        zones: [
          { id: 'z-agap-l', name: 'A-GAP (L)', cx: 310, cy: 200, rx: 25, ry: 20, color: '#058538', opacity: 0.15 },
          { id: 'z-agap-r', name: 'A-GAP (R)', cx: 390, cy: 200, rx: 25, ry: 20, color: '#058538', opacity: 0.15 },
        ],
      },
    ],
  },
  {
    id: 'de-drill-extra-1',
    category: 'DE',
    categoryLabel: 'Defensive Ends (DE)',
    title: 'CONTAIN-CRASH STUNT',
    subtitle: 'DE & DT Cross-Exchange Blitz',
    objective: 'Defensive Tackle slants hard into C-gap to draw the offensive tackle, while the Defensive End loops tightly into B-gap behind him to sack the QB.',
    setup: 'Offensive side sets Center, Right Guard, Right Tackle, and QB in shotgun. Defensive Tackle aligns in 3-tech on Right Guard; Defensive End aligns in 5-tech on Right Tackle.',
    instructions: [
      'Call "Crash! Crash!" to signal the cross-exchange stunt between DT and DE.',
      'On the snap, DT takes a hard outside step, slanting across the tackle’s face to occupy both Guard and Tackle.',
      'DE lets DT cross first, plants outside foot, and loops tightly off the DT’s hip into the vacated B-gap.',
      'DE keeps shoulders square as they penetrate into the pocket and flattens directly to the QB launch point.',
      'Execute a two-hand swipe to strip the football before bringing the passer to the turf.',
    ],
    equipment: 'Hand shields, cones, ball.',
    cues: ['"DE loop tight around DT’s hip!"', '"DT pin the offensive tackle inside!"', '"Fast burst to QB pocket!"'],
    faults: ['DE looping too wide and losing pursuit angle.', 'DT hesitating on the slant.'],
    phases: [
      {
        name: 'PHASE 1: STUNT PENETRATION',
        description: 'Snap: DT crashes hard through tackle outside shoulder; DE plants outside foot and loops around into B-gap.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 330, y: 200, color: '#1e293b', isSquare: true },
          { id: 'o-rg', type: 'O', label: 'RG', x: 400, y: 200, color: '#1e293b' },
          { id: 'o-rt', type: 'O', label: 'RT', x: 470, y: 200, color: '#1e293b' },
          { id: 'o-qb', type: 'O', label: 'QB', x: 330, y: 130, color: '#b91c1c' },
          { id: 'd-dt', type: 'X', label: 'DT', x: 400, y: 270, color: '#2563eb' },
          { id: 'd-de', type: 'X', label: 'DE', x: 485, y: 275, color: '#058538' },
        ],
        arrows: [
          { id: 'a-dt-slant', type: 'straight', startX: 400, startY: 260, endX: 460, endY: 215, color: '#2563eb', label: 'C-Gap Crash' },
          { id: 'a-de-loop', type: 'curved', startX: 485, startY: 265, endX: 360, endY: 145, controlX: 440, controlY: 230, color: '#058538', label: 'B-Gap Loop' },
        ],
        zones: [
          { id: 'z-pocket', name: 'QB TARGET', cx: 330, cy: 130, rx: 38, ry: 22, color: '#b91c1c', opacity: 0.15 },
        ],
      },
    ],
  },
  {
    id: 'lb-drill-extra-1',
    category: 'LB',
    categoryLabel: 'Linebackers (LB)',
    title: 'SCRAPE-AND-SPILL PULLING GUARD',
    subtitle: 'Trap & Power Counter Response',
    objective: 'Offense pulls the backside guard. Play-side LB diagnoses pull immediately, scrapes downhill with hips square, and attacks the pulling guard with inside leverage.',
    setup: 'Set offensive line with Center and Left Guard. Place Running Back at 4 yards depth angled toward the right B-gap. Middle Linebacker aligns at 4.5 yards depth stacked over center; Will Linebacker at 4.5 yards over Left Guard.',
    instructions: [
      'Linebackers read the offensive guard’s helmet on the snap.',
      'If the guard pulls across the center, shout "Pull! Pull!" and initiate immediate downhill lateral shuffle.',
      'Do not get sucked into the line of scrimmage or caught behind trash.',
      'Attack the pulling guard with the inside shoulder ("wrong-arm" technique) to bounce the running back wider.',
      'Keep eyes up, maintain outside leverage, and allow trailing pursuit to clean up the play.',
    ],
    equipment: 'Hand shields, cones, ball.',
    cues: ['"Read the guard’s helmet!"', '"Pulling guard brings you to the ball!"', '"Wrong-arm the kickout block!"'],
    faults: ['Getting caught behind trash in the middle.', 'Turning sideways and losing square vision.'],
    phases: [
      {
        name: 'PHASE 1: GUARD READ & DOWNHILL SCRAPE',
        description: 'Offensive guard pulls right. Middle linebacker reads pulling helmet and fills the alley with violent downhill momentum.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 350, y: 200, color: '#1e293b', isSquare: true },
          { id: 'o-lg', type: 'O', label: 'LG', x: 280, y: 200, color: '#ea580c', subLabel: 'PULLING' },
          { id: 'o-rb', type: 'O', label: 'RB', x: 420, y: 150, color: '#b91c1c' },
          { id: 'd-mlb', type: 'letter', label: 'M', x: 350, y: 325, color: '#0f172a' },
          { id: 'd-wlb', type: 'letter', label: 'W', x: 275, y: 325, color: '#0f172a' },
        ],
        arrows: [
          { id: 'a-pull', type: 'curved', startX: 280, startY: 200, endX: 415, endY: 185, controlX: 345, controlY: 175, color: '#ea580c', label: 'Guard Pull' },
          { id: 'a-mlb-scrape', type: 'blitz', startX: 350, startY: 315, endX: 410, endY: 200, color: '#058538', label: 'Downhill Spill' },
        ],
        zones: [
          { id: 'z-meet', name: 'SPILL COLLISION POINT', cx: 415, cy: 195, rx: 42, ry: 22, color: '#058538', opacity: 0.18 },
        ],
      },
    ],
  },
  {
    id: 'db-drill-extra-1',
    category: 'DB',
    categoryLabel: 'Defensive Backs (DB)',
    title: 'OPEN-FIELD FORCE & ALLEY TACKLE',
    subtitle: 'Cornerback Boundary Contain & Alley Fill',
    objective: 'Cornerback locks eyes on running back bouncing to sideline. CB refuses to be blocked inside, sets edge, forces runner back inside to linebacker help.',
    setup: 'Set 4 cones marking a 10x15 yard sideline alley. Wide Receiver lines up on numbers; Cornerback aligns 6 yards off with inside leverage. Running back starts in backfield with ball.',
    instructions: [
      'Cornerback maintains 6 yards cushion with hips at 45° angle facing inside toward the ball.',
      'On run commit, attack the stalk-blocking receiver with violent shock hands to the chest.',
      'Keep the outside arm and leg free to seal the boundary—never allow the ballcarrier to reach the sideline.',
      'Force the ballcarrier to cut back inside into the teeth of the rallying Free Safety and Linebacker pursuit.',
      'If runner cuts inside, drive the near shoulder into the runner’s hip, wrap both legs, and roll to finish.',
    ],
    equipment: 'Cones marking sideline corridor, blocking pad, ball.',
    cues: ['"Keep outside arm free!"', '"Force runner back inside to your help!"', '"Near leg in the ground!"'],
    faults: ['Diving at legs and getting shoved out of bounds.', 'Allowing runner to get outside your helmet.'],
    phases: [
      {
        name: 'PHASE 1: STALK BLOCK DEFEAT & FORCE',
        description: 'WR stalks CB; CB punches WR chest with inside arm, keeps outside arm free to seal the boundary.',
        tokens: [
          { id: 'd-cb', type: 'letter', label: 'C', x: 550, y: 290, color: '#0f172a' },
          { id: 'o-wr', type: 'O', label: 'WR', x: 550, y: 200, color: '#64748b' },
          { id: 'o-rb', type: 'O', label: 'RB', x: 450, y: 155, color: '#b91c1c' },
          { id: 'd-fs', type: 'letter', label: 'FS', x: 410, y: 375, color: '#7c3aed' },
        ],
        arrows: [
          { id: 'a-cb-edge', type: 'blitz', startX: 550, startY: 280, endX: 515, endY: 185, color: '#2563eb', label: 'Outside Arm Free' },
          { id: 'a-fs-alley', type: 'blitz', startX: 410, startY: 365, endX: 465, endY: 185, color: '#7c3aed', label: 'Alley Cleanup' },
        ],
        zones: [
          { id: 'z-sideline', name: 'NO OUTSIDE BOUNCE', cx: 580, cy: 190, rx: 32, ry: 45, color: '#b91c1c', opacity: 0.15 },
        ],
      },
    ],
  },
  {
    id: 'lb-krausko-master',
    category: 'LB',
    categoryLabel: 'Linebackers (LB)',
    title: 'KRAUSKO LB BLITZ: 3-PHASE PROGRESSION (MASTER)',
    subtitle: 'Get Skinny, Inside Gap Combat & Edge Flatten',
    objective: 'Youth linebacker master blitz progression based on Krausko technique: (1) Snap shoulders sideways to "get skinny" through tight seams, (2) Attack inside blockers with hand-swipe/rip and re-square, (3) Dip inside shoulder and flatten around the edge without looping.',
    setup: 'Station width 15 yards. 2 blockers holding "The Colt" pads or hand shields spaced 3 feet apart. QB dummy positioned 5 yards behind the line. 4 boundary cones creating a clear blitz tunnel.',
    instructions: [
      'Station 1 ("Get Skinny"): Sprint through the 2-foot seam, snap shoulders 90° at contact, slide through without catching pad on chest, then instantly re-square and wrap dummy.',
      'Station 2 ("Chop & Rip"): Blocker extends hands; LB delivers a violent two-hand downward swipe to the wrists, rips opposite arm skyward, turns hips, and explodes through.',
      'Station 3 ("Dip & Flatten"): Rush outside tackle’s reach, slap hands, dip inside shoulder under the blocker’s chest, shave the cone, and flatten directly to QB launch point.',
    ],
    equipment: 'Krausko "The Colt" blocking pad or hand shields, 6 cones, football on stick.',
    cues: [
      '"Get skinny! Snap shoulders sideways to cut your target area in half!"',
      '"Violent hands! Chop the blocker’s wrists and rip to the sky!"',
      '"Re-square immediately! Once hips clear the pad, turn square to the QB!"',
      '"Dip & bend the edge — tight arc, no looping banana routes!"',
      '"Eyes up, hit the strike zone, and drive cleats through the target!"',
    ],
    faults: [
      'Hitting blockers chest-to-chest and getting stopped cold.',
      'Taking wide 5-yard looping arcs around blocks that waste valuable blitz time.',
      'Staying sideways after penetrating instead of snapping hips square to the QB.',
      'Dropping helmet or eyes at the point of contact.',
    ],
    phases: [
      {
        name: 'PHASE 1: "GET SKINNY IN THE HOLE" (SLIP SEAM)',
        description: 'Blocker holds pad in A/B-gap. LB triggers downhill on ball movement. At contact, snaps shoulders and hips 90° sideways to slip the seam, then instantly re-squares into the backfield.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 270, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-g', type: 'bag', label: 'PAD', x: 430, y: 240, color: '#ef4444', subLabel: 'The Colt Shield' },
          { id: 'c-l', type: 'cone', label: 'CHUTE', x: 200, y: 240, color: '#e06c00' },
          { id: 'c-r', type: 'cone', label: 'CHUTE', x: 500, y: 240, color: '#e06c00' },
          { id: 'd-lb', type: 'X', label: 'MLB', x: 350, y: 380, color: '#058538', subLabel: 'Blitz Stance' },
          { id: 'o-qb', type: 'O', label: 'QB', x: 350, y: 110, color: '#b91c1c', subLabel: 'Target' },
        ],
        arrows: [
          { id: 'a-trigger', type: 'straight', startX: 350, startY: 355, endX: 350, endY: 285, color: '#058538', label: 'Downhill Burst' },
          { id: 'a-skinny', type: 'curved', startX: 350, startY: 285, endX: 345, endY: 190, controlX: 320, controlY: 240, color: '#2563eb', label: 'Snap Shoulders 90° (Get Skinny)' },
          { id: 'a-resquare', type: 'blitz', startX: 345, startY: 190, endX: 350, endY: 135, color: '#058538', label: 'Re-Square & Sack' },
        ],
        zones: [
          { id: 'z-skinny', name: 'SLIP SEAM (2-FT CREASE)', cx: 350, cy: 240, rx: 46, ry: 24, color: '#2563eb', opacity: 0.16 },
          { id: 'z-sack', name: 'SACK & FINISH ZONE', cx: 350, cy: 110, rx: 48, ry: 24, color: '#058538', opacity: 0.16 },
        ],
      },
      {
        name: 'PHASE 2: "ATTACKING INSIDE GAP" (CHOP & RIP)',
        description: 'Blocker steps forward with active hands. LB attacks head-on, delivers a 2-hand downward chop to blocker wrists, violently rips opposite arm upward, snaps hips through, and re-squares.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 240, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-g', type: 'O', label: 'RG', x: 370, y: 240, color: '#1e293b', subLabel: 'Hands Out' },
          { id: 'd-lb', type: 'X', label: 'ILB', x: 440, y: 380, color: '#058538', subLabel: 'Attack Track' },
          { id: 'o-qb', type: 'O', label: 'QB', x: 260, y: 110, color: '#b91c1c', subLabel: 'Target' },
        ],
        arrows: [
          { id: 'a-approach', type: 'straight', startX: 440, startY: 355, endX: 405, endY: 275, color: '#058538', label: 'Downhill Strike' },
          { id: 'a-chop', type: 'straight', startX: 405, startY: 275, endX: 385, endY: 245, color: '#d91b24', label: 'Two-Hand Wrist Chop' },
          { id: 'a-rip-resquare', type: 'curved', startX: 385, startY: 245, endX: 285, endY: 135, controlX: 355, controlY: 185, color: '#2563eb', label: 'Chop-Rip & Re-Square' },
        ],
        zones: [
          { id: 'z-combat', name: 'WRIST CHOP POINT', cx: 395, cy: 255, rx: 48, ry: 24, color: '#d91b24', opacity: 0.16 },
          { id: 'z-rip-clear', name: 'CLEAR PENETRATION LANE', cx: 335, cy: 185, rx: 46, ry: 22, color: '#058538', opacity: 0.16 },
        ],
      },
      {
        name: 'PHASE 3: "ATTACKING OFF THE EDGE" (DIP & FLATTEN)',
        description: 'OLB blitzes off the offensive tackle edge. LB strikes OT outside reach with club/swipe, dips inside shoulder under OT breastplate, flattens line to QB launch point without looping.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 190, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-rg', type: 'O', label: 'RG', x: 270, y: 240, color: '#1e293b' },
          { id: 'o-rt', type: 'O', label: 'RT', x: 360, y: 240, color: '#1e293b', subLabel: 'Kick Step' },
          { id: 'o-qb', type: 'O', label: 'QB', x: 210, y: 110, color: '#b91c1c', subLabel: 'Pocket' },
          { id: 'c-bend1', type: 'cone', label: 'CORNER', x: 450, y: 240, color: '#e06c00' },
          { id: 'c-bend2', type: 'cone', label: 'APEX', x: 420, y: 175, color: '#e06c00' },
          { id: 'd-olb', type: 'X', label: 'OLB', x: 530, y: 370, color: '#058538', subLabel: 'Dog Blitz' },
        ],
        arrows: [
          { id: 'a-edge-burst', type: 'straight', startX: 530, startY: 345, endX: 470, endY: 250, color: '#058538', label: 'Speed Rush to Outside Hip' },
          { id: 'a-dip-bend', type: 'curved', startX: 470, startY: 250, endX: 355, endY: 150, controlX: 450, controlY: 170, color: '#2563eb', label: 'Dip Shoulder & Shave Cone' },
          { id: 'a-flatten-qb', type: 'blitz', startX: 355, startY: 150, endX: 235, endY: 120, color: '#058538', label: 'Flatten directly to QB' },
        ],
        zones: [
          { id: 'z-bend', name: 'BEND CORNER TRACK', cx: 430, cy: 190, rx: 50, ry: 28, color: '#2563eb', opacity: 0.16 },
          { id: 'z-qb-kill', name: 'QB STRIP SACK ZONE', cx: 210, cy: 110, rx: 46, ry: 24, color: '#b91c1c', opacity: 0.16 },
        ],
      },
    ],
  },
  {
    id: 'lb-krausko-skinny',
    category: 'LB',
    categoryLabel: 'Linebackers (LB)',
    title: 'KRAUSKO STATION 1: "GET SKINNY IN THE HOLE"',
    subtitle: 'Shoulder-Snap & Seam Slip Repetitions',
    objective: 'Rapid-fire station teaching youth linebackers to reduce their frontal surface area by violently turning shoulders sideways through tight gaps before re-squaring to make the tackle.',
    setup: 'Set 4 cones creating a 2-foot wide by 5-yard long chute alley. Blocker stands at midpoint holding hand shield or Krausko pad. Foam tackle dummy stands 3 yards past chute.',
    instructions: [
      'Linebacker starts in 2-point breakdown stance 3 yards back from chute.',
      'On whistle/snap, sprint aggressively into the chute alley.',
      'Exactly 1 foot before contact with the pad, violently rotate shoulders 90 degrees.',
      'Keep feet driving forward with pumping legs while sliding between blocker and boundary cone.',
      'The instant the hips clear the pad, drive outside cleat into the turf, snap shoulders square, wrap the tackle dummy, and squeeze thighs.',
    ],
    equipment: '2 hand shields / "The Colt" pads, 4 cones marking 2-foot alley, football.',
    cues: [
      '"Turn your shoulders 90° right at the collision point!"',
      '"Slide like a sheet of paper between the blocker and center!"',
      '"Once your back hip clears, punch your cleats into the turf and re-square!"',
      '"Never stop your feet while turning!"',
    ],
    faults: [
      'Hitting the pad head-on with numbers.',
      'Slowing down or stopping feet while attempting to turn.',
      'Failing to re-square after slipping the pad, leaving the tackle angle awkward.',
    ],
    phases: [
      {
        name: 'PHASE 1: CHUTE SPRINT & SEAM SLIP',
        description: 'Coach holds pad simulating offensive guard. LB sprints into chute, snaps shoulders sideways at the 1-yard mark, slices through the 2-foot crease, and explodes to tackle dummy.',
        tokens: [
          { id: 'c-l1', type: 'cone', label: 'CHUTE', x: 250, y: 310, color: '#e06c00' },
          { id: 'c-r1', type: 'cone', label: 'CHUTE', x: 450, y: 310, color: '#e06c00' },
          { id: 'c-l2', type: 'cone', label: 'CHUTE', x: 250, y: 210, color: '#e06c00' },
          { id: 'c-r2', type: 'cone', label: 'CHUTE', x: 450, y: 210, color: '#e06c00' },
          { id: 'o-c', type: 'square', label: 'C', x: 295, y: 255, color: '#1e293b', isSquare: true },
          { id: 'pad-1', type: 'bag', label: 'PAD', x: 405, y: 255, color: '#ef4444', subLabel: 'The Colt Shield' },
          { id: 'd-lb', type: 'X', label: 'LB', x: 350, y: 410, color: '#058538', subLabel: '2-Pt Stance' },
          { id: 'dummy', type: 'bag', label: 'TACKLE', x: 350, y: 100, color: '#0284c7', subLabel: 'Dummy Target' },
        ],
        arrows: [
          { id: 'a-entry', type: 'straight', startX: 350, startY: 385, endX: 350, endY: 305, color: '#058538', label: 'Downhill Sprint' },
          { id: 'a-snap', type: 'curved', startX: 350, startY: 305, endX: 345, endY: 200, controlX: 325, controlY: 255, color: '#2563eb', label: 'Snap Shoulders 90°' },
          { id: 'a-exit', type: 'blitz', startX: 345, startY: 200, endX: 350, endY: 130, color: '#058538', label: 'Re-Square & Wrap' },
        ],
        zones: [
          { id: 'z-chute', name: '2-FOOT CHUTE ALLEY', cx: 350, cy: 255, rx: 70, ry: 35, color: '#e06c00', opacity: 0.14 },
          { id: 'z-wrap', name: 'FORM TACKLE WRAP', cx: 350, cy: 100, rx: 48, ry: 24, color: '#058538', opacity: 0.18 },
        ],
      },
    ],
  },
  {
    id: 'lb-krausko-inside',
    category: 'LB',
    categoryLabel: 'Linebackers (LB)',
    title: 'KRAUSKO STATION 2: INSIDE GAP HAND COMBAT & RIP',
    subtitle: 'Chop, Rip & Violent Disengagement',
    objective: 'Linebacker learns to neutralize an interior offensive lineman’s punch using violent two-hand swipes or chops, followed immediately by an explosive upward arm rip and hip turn.',
    setup: 'Blocker stands holding shield with extended hand arm-guards at the line of scrimmage. Quarterback stand-in stands 4 yards behind blocker. Linebacker aligns 3 yards off in blitz track.',
    instructions: [
      'Linebacker fires downhill toward the offensive guard’s outside shoulder.',
      'As blocker extends both hands, deliver a violent two-hand downward chop across blocker’s forearms/wrists.',
      'Simultaneously rip the trailing arm straight upward like an uppercut under the blocker’s armpit.',
      'Rotate hips forward through the crease while ripping to break the blocker’s reach.',
      'Re-square both shoulders immediately and close out on the quarterback with high motor.',
    ],
    equipment: 'Blocking shield with arm extensions or coach holding pad, cones, football.',
    cues: [
      '"Chop the blocker’s wrists down violently!"',
      '"Rip your back arm to the clouds — get under their shoulder pad!"',
      '"Drive your inside hip through their outside hip!"',
      '"Re-square and burst straight toward the quarterback!"',
    ],
    faults: [
      'Trying to push the blocker with both hands instead of knocking their arms away.',
      'Lazy arm rip that gets caught on the blocker’s chest.',
      'Allowing the blocker to get their hands inside your chest plate.',
    ],
    phases: [
      {
        name: 'PHASE 1: ATTACK PUNCH & TWO-HAND CHOP',
        description: 'Blocker punches out both hands. LB attacks the wrists with a violent two-hand downward swipe to break the blocker’s leverage.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 240, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-g', type: 'O', label: 'OG', x: 360, y: 240, color: '#1e293b', subLabel: 'Punching' },
          { id: 'd-lb', type: 'X', label: 'LB', x: 440, y: 380, color: '#058538', subLabel: 'Attacking' },
          { id: 'qb', type: 'O', label: 'QB', x: 270, y: 110, color: '#b91c1c', subLabel: 'Target' },
        ],
        arrows: [
          { id: 'a-punch-strike', type: 'straight', startX: 440, startY: 355, endX: 395, endY: 275, color: '#058538', label: 'Attack Outside Arm' },
          { id: 'a-chop-hands', type: 'straight', startX: 395, startY: 275, endX: 365, endY: 245, color: '#d91b24', label: 'Downward Wrist Chop' },
        ],
        zones: [
          { id: 'z-strike', name: 'POINT OF WRIST ATTACK', cx: 380, cy: 255, rx: 45, ry: 22, color: '#d91b24', opacity: 0.18 },
        ],
      },
      {
        name: 'PHASE 2: VIOLENT RIP & HIP EXPLOSION',
        description: 'With blocker arms swiped downward, LB violently rips the right arm skyward, turns hips through the gap, and explodes into the backfield.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 240, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-g', type: 'O', label: 'OG', x: 375, y: 240, color: '#64748b', subLabel: 'Neutralized' },
          { id: 'd-lb', type: 'X', label: 'LB', x: 315, y: 215, color: '#058538', subLabel: 'Sky Rip & Hip Turn' },
          { id: 'qb', type: 'O', label: 'QB', x: 270, y: 110, color: '#b91c1c', subLabel: 'Sacked' },
        ],
        arrows: [
          { id: 'a-sky-rip', type: 'curved', startX: 345, startY: 265, endX: 315, endY: 185, controlX: 295, controlY: 225, color: '#2563eb', label: 'Sky Rip & Hip Turn' },
          { id: 'a-finish', type: 'blitz', startX: 315, startY: 185, endX: 275, endY: 135, color: '#058538', label: 'Re-Square & Sack' },
        ],
        zones: [
          { id: 'z-rip', name: 'HIP CLEARANCE ALLEY', cx: 315, cy: 215, rx: 42, ry: 24, color: '#2563eb', opacity: 0.18 },
          { id: 'z-finish', name: 'SACK IMPACT POINT', cx: 270, cy: 110, rx: 45, ry: 22, color: '#058538', opacity: 0.18 },
        ],
      },
    ],
  },
  {
    id: 'lb-krausko-edge',
    category: 'LB',
    categoryLabel: 'Linebackers (LB)',
    title: 'KRAUSKO STATION 3: EDGE DOG BLITZ (DIP & FLATTEN)',
    subtitle: 'Hoop Bend & Quarterback Launch Point Attack',
    objective: 'Outside linebacker / edge rusher learns how to defeat an offensive tackle’s pass set, dip the inside shoulder around the corner without losing speed, and flatten the rush path directly into the QB.',
    setup: 'Offensive tackle aligns at line of scrimmage. Set 2 orange agility cones in an arc 2 yards outside the tackle representing the rush bend track. QB stands at 6 yards depth.',
    instructions: [
      'Edge rusher starts outside tackle with outside foot back in sprinter stance.',
      'Explode out of stance on the snap, taking 2 fast strides threatening the tackle’s outside edge.',
      'As tackle reaches with outside hand, club/swipe the wrist with outside forearm.',
      'Dip the inside shoulder low toward the grass (shaving the cones) without losing stride frequency.',
      'Point eyes and hips directly at the quarterback’s back hip, flatten the rush line, and secure the sack.',
    ],
    equipment: 'Agility hoop or 3 curved cones, blocking shield, football.',
    cues: [
      '"First two steps must threaten the tackle’s outside foot!"',
      '"Swipe the tackle’s outside arm and drop your inside shoulder!"',
      '"Shave the corner — touch the cone on your bend!"',
      '"Flatten immediately at 5 yards — don’t run 10 yards deep into nowhere!"',
    ],
    faults: [
      'Running too deep (banana loop) and giving the QB an easy escape up in the pocket.',
      'Slowing down when turning the corner instead of driving into the bend.',
      'Failing to locate the football before leaving your rush angle.',
    ],
    phases: [
      {
        name: 'PHASE 1: THREATEN OUTSIDE & CLUB-SWIPE',
        description: 'LB gets off ball, attacks OT outside shoulder. OT reaches to kick-slide; LB clubs the punch and lowers center of gravity.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 190, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-g', type: 'O', label: 'RG', x: 270, y: 240, color: '#1e293b' },
          { id: 'o-rt', type: 'O', label: 'OT', x: 360, y: 240, color: '#1e293b', subLabel: 'Kick Slide' },
          { id: 'd-olb', type: 'X', label: 'OLB', x: 530, y: 370, color: '#058538', subLabel: 'Edge Rusher' },
          { id: 'c-hoop1', type: 'cone', label: 'TURN', x: 460, y: 240, color: '#e06c00' },
          { id: 'c-hoop2', type: 'cone', label: 'APEX', x: 420, y: 175, color: '#e06c00' },
          { id: 'qb', type: 'O', label: 'QB', x: 210, y: 110, color: '#b91c1c', subLabel: 'Pocket' },
        ],
        arrows: [
          { id: 'a-speed', type: 'straight', startX: 530, startY: 345, endX: 475, endY: 255, color: '#058538', label: 'Threaten Outside Hip' },
          { id: 'a-club', type: 'straight', startX: 475, startY: 255, endX: 400, endY: 240, color: '#d91b24', label: 'Club Outside Hand' },
        ],
        zones: [
          { id: 'z-edge-set', name: 'EDGE COMBAT POINT', cx: 440, cy: 250, rx: 50, ry: 26, color: '#d91b24', opacity: 0.18 },
        ],
      },
      {
        name: 'PHASE 2: DIP SHOULDER & FLATTEN TO QB POCKET',
        description: 'LB dips inside shoulder low around the hoop cones, points hips directly at QB launch point, and delivers closing burst.',
        tokens: [
          { id: 'o-c', type: 'square', label: 'C', x: 190, y: 240, color: '#1e293b', isSquare: true },
          { id: 'o-g', type: 'O', label: 'RG', x: 270, y: 240, color: '#1e293b' },
          { id: 'o-rt', type: 'O', label: 'OT', x: 360, y: 240, color: '#64748b', subLabel: 'Beaten Outside' },
          { id: 'd-olb', type: 'X', label: 'OLB', x: 350, y: 150, color: '#058538', subLabel: 'Flattened' },
          { id: 'qb', type: 'O', label: 'QB', x: 210, y: 110, color: '#b91c1c', subLabel: 'In Sights' },
          { id: 'c-hoop2', type: 'cone', label: 'APEX', x: 420, y: 175, color: '#e06c00' },
        ],
        arrows: [
          { id: 'a-dip-corner', type: 'curved', startX: 470, startY: 245, endX: 350, endY: 150, controlX: 435, controlY: 170, color: '#2563eb', label: 'Low Shoulder Dip' },
          { id: 'a-flatten-sack', type: 'blitz', startX: 350, startY: 150, endX: 235, endY: 115, color: '#058538', label: 'Flatten Directly to QB' },
        ],
        zones: [
          { id: 'z-sack-pocket', name: 'STRIP SACK IMPACT', cx: 210, cy: 110, rx: 48, ry: 24, color: '#058538', opacity: 0.22 },
        ],
      },
    ],
  },
];
